version: '3.3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64 #específico para Mac M1
    environment:
      MYSQL_DATABASE: 'drone'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
