version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:database
  mysql:
     image: mysql:8.0
     restart: always
     environment:
      MYSQL_DATABASE: 'dronedb'
      MYSQL_ROOT_PASSWORD: 'root'
     ports:
       - 3306:3306
     volumes:
      - drone-db:/var/lib/mysql
      
volumes:
  drone-db:
